**Step-1:Import packages**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

**Step-2: Create a Data Frame using a List**

In [5]:
names=['Ramesh','Suresh','Satish','Mahesh']
#pd.DataFrame(data,index,columns)
pd.DataFrame(names)

        0
0  Ramesh
1  Suresh
2  Satish
3  Mahesh

**Step-3: I want to change the index**

In [7]:
names=['Ramesh','Suresh','Satish','Mahesh']
ids=['A','B','C','D']
pd.DataFrame(names,ids)

        0
A  Ramesh
B  Suresh
C  Satish
D  Mahesh

**Step-4: Add the columns**

In [8]:
names=['Ramesh','Suresh','Satish','Mahesh']
ids=['A','B','C','D']
cols=['Names']
pd.DataFrame(names,ids,cols)

    Names
A  Ramesh
B  Suresh
C  Satish
D  Mahesh

**Step-5: Data and Columns**

In [9]:
names=['Ramesh','Suresh','Satish','Mahesh']
cols=['Names']
pd.DataFrame(names,columns=cols)

    Names
0  Ramesh
1  Suresh
2  Satish
3  Mahesh

In [11]:
names=['Ramesh','Suresh']
pd.DataFrame(names,[1,2],['Names'])

    Names
1  Ramesh
2  Suresh

**Step-6: Multiple columns**

In [13]:
names=['Ramesh','Suresh','Satish','Mahesh']
age=[20,22,24,26]
pd.DataFrame(zip(names,age))

        0   1
0  Ramesh  20
1  Suresh  22
2  Satish  24
3  Mahesh  26

In [14]:
names=['Ramesh','Suresh','Satish','Mahesh']
age=[20,22,24,26]
pd.DataFrame(zip(names,age),columns=['Names','Age'])

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24
3  Mahesh   26

In [17]:
names=['Ramesh','Suresh','Satish','Mahesh']
age=[20,22,24,26]
cols=['Names','Age']
df=pd.DataFrame(zip(names,age),columns=cols)
df

    Names  Age
0  Ramesh   20
1  Suresh   22
2  Satish   24
3  Mahesh   26

**Step-7: Add a new column to already existed data frame**

- in above first we have taken data 

- then created a data frame 

- now we want to add new data based on requirement

In [23]:
city=['Hyderabad','Pune','Bengaluru','Guntur']
df['City']=city
df

    Names  Age       City
0  Ramesh   20  Hyderabad
1  Suresh   22       Pune
2  Satish   24  Bengaluru
3  Mahesh   26     Guntur

In [24]:
df['Marks']=[20,30,25,35]
df

    Names  Age       City  Marks
0  Ramesh   20  Hyderabad     20
1  Suresh   22       Pune     30
2  Satish   24  Bengaluru     25
3  Mahesh   26     Guntur     35

**Step-8: Update the column with new values**

In [27]:
df['Marks']=[200,300,400,500]

In [28]:
df

    Names  Age       City  Marks
0  Ramesh   20  Hyderabad    200
1  Suresh   22       Pune    300
2  Satish   24  Bengaluru    400
3  Mahesh   26     Guntur    500

**Step-9: Create empty data frame and add the columns**

In [30]:
df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[20,22,24]
df['City']=['Hyderbad','Bengaluru','Pune']
df

    Names  Age       City
0  Ramesh   20   Hyderbad
1  Suresh   22  Bengaluru
2  Satish   24       Pune

**Step-10: Create a dataframe using a dictionary**

d={'Names':['Ramesh','Suresh','Satish'],
   'Age':[20,22,24],
   'City':['Hyd','Blr','Pune']}
df=pd.DataFrame(d)
df

In [34]:
d={'Names':'Ramesh',
   'Age':20,
   'City':'Hyd'}
df=pd.DataFrame(d)
df

ValueError: If using all scalar values, you must pass an index

In [5]:
d={'Names':'Ramesh',
   'Age':20,
   'City':'Hyd'}
df=pd.DataFrame(d,index=[0])
df

    Names  Age City
0  Ramesh   20  Hyd

**Step-11: Saving the data frame**

In [37]:
df.to_csv('data.csv')

In [38]:
df.to_excel('data.xlsx')

In [39]:
df.to_csv(r'C:\Users\Dell\OneDrive\Documents\data.csv')

**Step-12: How to read the data frame**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# in order to read th data 
# filename.ext
# open(mbox-short.txt).read()
# open(dummy.txt,mode='w').write('hello')
pd.read_csv('data.csv')

   Unnamed: 0   Names  Age City
0           0  Ramesh   20  Hyd

In [6]:
df

    Names  Age City
0  Ramesh   20  Hyd

In [8]:
pd.read_excel('data.xlsx')

   Unnamed: 0   Names  Age City
0           0  Ramesh   20  Hyd

In [14]:
d={'Names':['Ramesh','Suresh','Mahesh'],
   'Age':[20,22,24],
   'City':['Hyd','Pune','Blr']}
df=pd.DataFrame(d)
df

    Names  Age  City
0  Ramesh   20   Hyd
1  Suresh   22  Pune
2  Mahesh   24   Blr

In [ ]:
df.to_csv
pd.read_csv

df.to_excel
pd.read_excel

In [17]:
df.to_csv('data.csv',index=False)

In [18]:
pd.read_csv('data.csv')

    Names  Age  City
0  Ramesh   20   Hyd
1  Suresh   22  Pune
2  Mahesh   24   Blr

In [19]:
df['Marks']=[45,37,48]
df

    Names  Age  City  Marks
0  Ramesh   20   Hyd     45
1  Suresh   22  Pune     37
2  Mahesh   24   Blr     48

**Step-13: Drop the column**

- labels

- axis

- index

- columns

- inplace

In [22]:
df.drop(columns='Marks')

    Names  Age  City
0  Ramesh   20   Hyd
1  Suresh   22  Pune
2  Mahesh   24   Blr

In [26]:
df

    Names  Age  City  Marks
0  Ramesh   20   Hyd     45
1  Suresh   22  Pune     37
2  Mahesh   24   Blr     48

In [24]:
df.drop(1)

    Names  Age City  Marks
0  Ramesh   20  Hyd     45
2  Mahesh   24  Blr     48

In [25]:
df

    Names  Age  City  Marks
0  Ramesh   20   Hyd     45
1  Suresh   22  Pune     37
2  Mahesh   24   Blr     48

In [27]:
df.drop(columns=['Marks','Age'])

    Names  City
0  Ramesh   Hyd
1  Suresh  Pune
2  Mahesh   Blr

In [28]:
df

    Names  Age  City  Marks
0  Ramesh   20   Hyd     45
1  Suresh   22  Pune     37
2  Mahesh   24   Blr     48

In [ ]:
df.drop(index=1)
df.drop(columns='Marks')
===============================
df.drop('Marks') # if i dont give argument label
df.drop(1) # 1 become label
================================
# we need to provide axis
# axis=0 indicates index
# axis=1 indicates columns

In [34]:
df.drop('Marks')

KeyError: "['Marks'] not found in axis"

In [33]:
df.drop('Marks',axis=0)

KeyError: "['Marks'] not found in axis"

In [32]:
df.drop('Marks',axis=1)

    Names  Age  City
0  Ramesh   20   Hyd
1  Suresh   22  Pune
2  Mahesh   24   Blr

**inplace**

- when we do the operation the result output is not overwriting

- means the original data frame is same as it is

- in order to do this we need use **inplace**

- by default inplace=False

- make **inplace=True** if you want to overwrite the result

In [36]:
df.drop('Marks',axis=1,inplace=True)

In [37]:
df

    Names  Age  City
0  Ramesh   20   Hyd
1  Suresh   22  Pune
2  Mahesh   24   Blr

**Step-14: Rename the column**

In [43]:
df.rename({'City':'city'},axis=1,inplace=True)

In [44]:
df

    Names  Age  city
0  Ramesh   20   Hyd
1  Suresh   22  Pune
2  Mahesh   24   Blr

In [47]:
df.rename({2:'B'},inplace=True)

In [48]:
df

    Names  Age  city
0  Ramesh   20   Hyd
1  Suresh   22  Pune
B  Mahesh   24   Blr

In [59]:
x=list(range(1,11))
y=[i*i for i in x]
z=[i**3 for i in x]
df=pd.DataFrame(zip(x,y,z),columns=['X','Y','Z'])
df

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

- len

- shape : df.shape

- size : df.size

- head : df.head

- tail : df.tail

- isnull : df.isnull

- dtypes : df.dtypes

- info : df.info

In [65]:
df.shape

(10, 3)

In [66]:
df.size

30

In [73]:
df.head()

   X   Y    Z
0  1   1    1
1  2   4    8
2  3   9   27
3  4  16   64
4  5  25  125

In [74]:
df.head(15)

    X    Y     Z
0   1    1     1
1   2    4     8
2   3    9    27
3   4   16    64
4   5   25   125
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [77]:
df.tail()

    X    Y     Z
5   6   36   216
6   7   49   343
7   8   64   512
8   9   81   729
9  10  100  1000

In [83]:
df.isnull()

       X      Y      Z
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False
6  False  False  False
7  False  False  False
8  False  False  False
9  False  False  False

In [82]:
df.isnull().sum()

X    0
Y    0
Z    0
dtype: int64

In [80]:
df.dtypes

X    int64
Y    int64
Z    int64
dtype: object

In [81]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   X       10 non-null     int64
 1   Y       10 non-null     int64
 2   Z       10 non-null     int64
dtypes: int64(3)
memory usage: 372.0 bytes

In [84]:
len(df)

10

**Step-15: Select a Columns**

In [85]:
df.columns

Index(['X', 'Y', 'Z'], dtype='object')

In [86]:
df['X']

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: X, dtype: int64

In [87]:
df[['X','Y']]

    X    Y
0   1    1
1   2    4
2   3    9
3   4   16
4   5   25
5   6   36
6   7   49
7   8   64
8   9   81
9  10  100

In [90]:
type(df['X']) # 1D

pandas.core.series.Series

In [91]:
type(df[['X','Y']]) #2D

pandas.core.frame.DataFrame

In [92]:
df['X'].shape

(10,)

In [93]:
df[['X','Y']].shape

(10, 2)

In [98]:
df # entire dataframe
df['Z'] # selecting one column
df['Z'].values # extracting the data

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000])

In [101]:
df['Z'].values.tolist()

[1, 8, 27, 64, 125, 216, 343, 512, 729, 1000]

In [99]:
df[['Y','Z']].values

array([[   1,    1],
       [   4,    8],
       [   9,   27],
       [  16,   64],
       [  25,  125],
       [  36,  216],
       [  49,  343],
       [  64,  512],
       [  81,  729],
       [ 100, 1000]])